ewz_recaptcha:
  version: 3
  enabled: true
  public_key: "%env(EWZ_RECAPTCHA_SITE_KEY)%"
  private_key: "%env(EWZ_RECAPTCHA_SECRET)%"
#  hide_badge: true
#  score_threshold: 0.6
  api_host: recaptcha.net
